services:
  - type: web
    name: parkpro-backend
    env: docker
    plan: free  # use "starter" or higher if you outgrow free tier
    region: frankfurt  # or oregon, singapore, etc.
    branch: main
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_EdpbutH1Q6Lm@ep-autumn-frost-a1ui69v5-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SECRET_KEY
        generateValue: true
